### ISSUE TITLE
Deleting an item in Bring does not result in it's removal in HA

### ISSUE THREAD

**Issue by dimatx** [vlebourl/shopping_list#11]
Adding and checking-off items in Bring results in the items correctly being synced to HA. However, it looks like if you delete an item in Bring (press and hold, settings, 'delete item'), it doesn't get removed from HA's list. It's becomes effectively orphaned in HA, until it is checked-off / renamed there.

**Comment by Camatobe** [comment]
Bring is not instantly synced with HA.
I quote the doc:

> Items added, checked or removed from the list in HA are automatically synced with your Bring list. Items added to or removed from your Bring list needs to be synced back to HA. The Bring -> HA sync is done every time an item is modified in HA's list, but HA has no way of knowing when Bring is modified... 

I hope you did as the documentation stated:
Constantly sync your HA with bring with `shopping_list.bring_sync` (Documented here: https://github.com/vlebourl/shopping_list#sync-from-bring-to-ha)

For example: I sync every 13min. And also everytime I walk by my Wall-iPad which is displaying the shopping-list. 
(Triggered by Motion-Sensor)

If this not solves your issue: Please provide Addonversion, HA-Version, Log-Errors etc.

**Comment by dimatx** [comment]
Yes, @Camatobe. I am syncing as described, this issue is not with adding items and checking them off in Bring. That's working as expected. It's specifically with the 'delete' functionality in Bring, which isn't working.

**Comment by Camatobe** [comment]
Ah I see! I misunderstood there.
I didn't even know deleting something in Bring is a thing for daily usage - was thinking this is only used to delete a typo.

But I can reproduce this too. Deleting an item from the recents list will not delete it in HA.

**Comment by jpoeppelman1** [comment]
I have this problem as well, can we expect a fix?

**Comment by vlebourl** [comment]
Hey guys, sorry for not answering. This repo is not under development due to lack of time... If any one is willing to claim ownership, I'll be happy to transfer it! Otherwise, I'll archive it as I won't be able to put any work into it for now...
