### ISSUE TITLE
Add another list to sync with HA

### ISSUE THREAD

**Issue by PatrykMadej** [vlebourl/shopping_list#12]
Hi,

Great job, how can I add a second list? I have a shopping list, and I want to add "To do" 
![Screenshot_20211101-093204_Home Assistant](https://user-images.githubusercontent.com/92501422/139657494-32ad6a2f-51d0-4893-97eb-b671077bf381.jpg)

**Comment by vlebourl** [comment]
Hey guys, sorry for not answering. This repo is not under development due to lack of time... If any one is willing to claim ownership, I'll be happy to transfer it! Otherwise, I'll archive it as I won't be able to put any work into it for now...
