### ISSUE TITLE
Adding items using voice command

### ISSUE THREAD

**Issue by julianoes** [vlebourl/shopping_list#13]
Hi Vincent and thanks for this integration.
I was able to make it work with my home assistant installation.

My question is whether you or anyone else using this has been able to integrate it with voice commands, e.g. Almond or Rhasspy. In my opinion, a voice skill like "Add X to shopping list" would really make this useful, right?

**Comment by vlebourl** [comment]
TBH I didn't use this integration in a while ^^'
But if I recall correctly, Bring does work with Google assistant. Just have to definite it as the default list app. https://www.getbring.com/blog-posts/google-assistant-notes-lists

Back when I wrote this project, it did work with my Google nest !

**Comment by vlebourl** [comment]
Just tested it, and it still works! Only draw back is there is no way for home assistant to know Bring! was updated nor for Bring! to push notification. Hence the section on the Readme on syncing Bring! back to HA https://github.com/vlebourl/shopping_list#sync-from-bring-to-ha

**Comment by julianoes** [comment]
> But if I recall correctly, Bring does work with Google assistant.

Yes, that's what I've been using so far but I find the Google assistant annoying as it always wants to guess the person it is talking to and often complains about "voice match settings, blabla". That's one of the reasons why I'm tinkering with home assistant in the first place.

**Comment by julianoes** [comment]
I found that it would be quite some work to add all of the words required to Rhasspy to actually support a shopping list skill to work properly. I'm gonna give up for now and hope that this gets easier in the future ;).
