### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by jflefebvre06** [vlebourl/shopping_list#14]
Hello,

Since HA `2021.12.0b0` I get the following error on startup `Setup failed for shopping_list: Unable to import component: cannot import name 'HTTP_BAD_REQUEST' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)`

**Comment by vlebourl** [comment]
I'm have a look

**Comment by vlebourl** [comment]
Can you try this branch https://github.com/vlebourl/shopping_list/tree/Fix-http-const ?

**Comment by vlebourl** [comment]
Should be fixed with #15

**Comment by jflefebvre06** [comment]
Works fine thanks a lot for your quick fix
