### ISSUE TITLE
Refresh Shoping List Card on Lovelace after sync

### ISSUE THREAD

**Issue by thespillmonkey** [vlebourl/shopping_list#16]
You currently need to manually refresh the entire dashboard after every sync in order for the updates to show on the shoping list card.

**Comment by jpoeppelman1** [comment]
I have the same problem here.  This may be a problem with HA core.  Is there a workaround to refresh the card?

**Comment by vlebourl** [comment]
Hey guys, sorry for not answering. This repo is not under development due to lack of time... If any one is willing to claim ownership, I'll be happy to transfer it! Otherwise, I'll archive it as I won't be able to put any work into it for now...
