### ISSUE TITLE
Doesn't fire shopping_list_updated event when items change

### ISSUE THREAD

**Issue by lexiismadd** [vlebourl/shopping_list#20]
Hi @vlebourl 

I've noticed that the integration doesn't appear to be firing the 'shopping_list_updated' event whenever there is a change made to the HA shopping list by the integration.

Would it be possible to look in to this?  I use this event to trigger a sync to my Alexa shopping list as the Bring! Alexa skill isn't available in my country.

I'm using HA Core 2022.8.6 (in a Docker container)

Thanks!

**Comment by vlebourl** [comment]
Hi, unfortunately this integration isn't under development. I don't have the time to work on it anymore. Sorry for the inconvenience.
Cheers
