### ISSUE TITLE
Feature request: Select list / use multiple lists

### ISSUE THREAD

**Issue by Studentenfutter** [vlebourl/shopping_list#3]
Hi, thanks for the great addon, works very good so far!
Is it possible already to select one or multiple lists? Per default the first list for my account is available but no items from my other lists.

**Comment by vlebourl** [comment]
as there is only one list in HA, I'm not sure it would work well to have multiple lists from bring... so far only the default list from bring is synced

**Comment by Studentenfutter** [comment]
Fair enough. A selection feature would still be nice to have so that you can choose which list is used. For example I use two lists for different stores and could the most important one to home assistant.

**Comment by vlebourl** [comment]
how about that? it's in the latest beta


![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/5701372/99521080-3c63bc80-2994-11eb-99ca-392a73e4d921.gif)

**Comment by vlebourl** [comment]
List selection has been added in version 0.4.
