### ISSUE TITLE
Feature request: Make it optional to remove recently used Items from bring

### ISSUE THREAD

**Issue by Camatobe** [vlebourl/shopping_list#6]
This integration seems to treat recently checked items (in HomeAssistant) the same as recently used items (in Bring!).

**Szenario**:
I often use the "recently used items" in Bring, re-adding my last items, so I don't have to type them.

But in HomeAssistant I like my list clean and to display only the items in the list I have to buy.
So - I remove checked items in HomeAssistant.

But -> This action will remove every item in the Bring!-Section "Recently used" in the Bring!-App as well. 

Maybe making this part of the.sync optional would be great, so only the "red tiles in Bring!" are synced between Bring and HA.

Home Assistant does not need to sync the recent Items with the checked Items

HA Version: 0.117
custom_shopping_list Version: 0.3-beta 2

**Comment by vlebourl** [comment]
I guess it can be done, but honestly, I feel like it kind of defeats the purpose of synchronizing the lists, and I have other stuff to look at first...
Currently the UI isn't very clean with the default panel in HA, but the shopping list card (https://www.home-assistant.io/lovelace/shopping-list/) keeps items separated like in Bring.

**Comment by vlebourl** [comment]
Hey guys, sorry for not answering. This repo is not under development due to lack of time... If any one is willing to claim ownership, I'll be happy to transfer it! Otherwise, I'll archive it as I won't be able to put any work into it for now...
