### ISSUE TITLE
Need to re-configure device after every HA restart

### ISSUE THREAD

**Issue by giggo** [vlebourl/shopping_list#9]
Every time I restart Home Assistant I need to re-configure the integration. It also syncs the shopping list only once right after configure. Any idea?
Installation was done via HACS.
HA is 2020.12.1

![image](https://user-images.githubusercontent.com/213763/102725810-d7e0a800-4319-11eb-823b-8247eb8fca51.png)

**Comment by vlebourl** [comment]
not sure about the need to re-add the integration... never faced this. regarding sync, have you read this? does it cover your question? https://github.com/vlebourl/shopping_list#sync-from-bring-to-ha

**Comment by vlebourl** [comment]
i need to find a way to decouple it from the official shopping list. maybe that will fix your issue. I'll have a look this week

**Comment by giggo** [comment]
Syncing in both directions work as long as I do not restart HA. It seems it forget username/password when HA is restarted. I installed via HACS

**Comment by vlebourl** [comment]
Honestly I have no idea ATM why the restart does that. I'll try to investigate further... I've tried to decouple this integration from the core shopping list, but the shipping list is too deeply intertwined with the frontend to be easily replicated with another domain, so unfortunately for now I'll keep this integration as a custom that overrides the shipping list.

**Comment by giggo** [comment]
Actually I like the approach to override the shopping list....
Any logs I should look at?

**Comment by giggo** [comment]
Is this the right way to get the debug log for your component?
logger:
  default: warning
  logs:
    custom_components.shopping_list: debug

I do not see anything in the log. Amy other idea how to drill down into this?


Am 27. Dez. 2020, 13:48 +0100 schrieb Vincent Le Bourlot <notifications@github.com>:

**Comment by vlebourl** [comment]
Hey guys, sorry for not answering. This repo is not under development due to lack of time... If any one is willing to claim ownership, I'll be happy to transfer it! Otherwise, I'll archive it as I won't be able to put any work into it for now...
